(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.countries = [
          { GlobalArea_Id : "6", GlobalAreaName : "Afghanistan" },
          { GlobalArea_Id : "7", GlobalAreaName : "Azerbaijan" },
          { GlobalArea_Id : "8", GlobalAreaName : "Armenia" },
          { GlobalArea_Id : "9", GlobalAreaName : "Bahrain" },
          { GlobalArea_Id : "10", GlobalAreaName : "Bangladesh" },
          { GlobalArea_Id : "11", GlobalAreaName : "Bhutan" },
          { GlobalArea_Id : "12", GlobalAreaName : "Brunei Darussalam" },
          { GlobalArea_Id : "13", GlobalAreaName : "Cambodia" },
          { GlobalArea_Id : "14", GlobalAreaName : "China" },
          { GlobalArea_Id : "16", GlobalAreaName : "Georgia" },
          { GlobalArea_Id : "17", GlobalAreaName : "India" },
          { GlobalArea_Id : "18", GlobalAreaName : "Indonesia" },
          { GlobalArea_Id : "19", GlobalAreaName : "Iran" },
          { GlobalArea_Id : "20", GlobalAreaName : "Iraq" },
          { GlobalArea_Id : "21", GlobalAreaName : "Israel" },
          { GlobalArea_Id : "22", GlobalAreaName : "Japan" },
          { GlobalArea_Id : "23", GlobalAreaName : "Jordan" },
          { GlobalArea_Id : "24", GlobalAreaName : "Kazakhstan" },
          { GlobalArea_Id : "25", GlobalAreaName : "North Korea" },
          { GlobalArea_Id : "26", GlobalAreaName : "South Korea" },
          { GlobalArea_Id : "27", GlobalAreaName : "Kuwait" },
          { GlobalArea_Id : "28", GlobalAreaName : "Kyrgyzstan" },
          { GlobalArea_Id : "29", GlobalAreaName : "Laos" },
          { GlobalArea_Id : "30", GlobalAreaName : "Lebanon" },
          { GlobalArea_Id : "31", GlobalAreaName : "Malaysia" },
          { GlobalArea_Id : "32", GlobalAreaName : "Maldives" },
          { GlobalArea_Id : "33", GlobalAreaName : "Mongolia" },
          { GlobalArea_Id : "34", GlobalAreaName : "Myanmar" },
          { GlobalArea_Id : "35", GlobalAreaName : "Nepal" },
          { GlobalArea_Id : "36", GlobalAreaName : "Oman" },
          { GlobalArea_Id : "37", GlobalAreaName : "Pakistan" },
          { GlobalArea_Id : "38", GlobalAreaName : "Philippines" },
          { GlobalArea_Id : "39", GlobalAreaName : "Qatar" },
          { GlobalArea_Id : "40", GlobalAreaName : "Saudi Arabia" },
          { GlobalArea_Id : "41", GlobalAreaName : "Singapore" },
          { GlobalArea_Id : "42", GlobalAreaName : "Sri Lanka" },
          { GlobalArea_Id : "43", GlobalAreaName : "Syria" },
          { GlobalArea_Id : "44", GlobalAreaName : "Tajikistan" },
          { GlobalArea_Id : "45", GlobalAreaName : "Thailand" },
          { GlobalArea_Id : "46", GlobalAreaName : "East Timor" },
          { GlobalArea_Id : "47", GlobalAreaName : "Turkey" },
          { GlobalArea_Id : "48", GlobalAreaName : "Turkmenistan" },
          { GlobalArea_Id : "49", GlobalAreaName : "United Arab Emirates" },
          { GlobalArea_Id : "50", GlobalAreaName : "Uzbekistan" },
          { GlobalArea_Id : "51", GlobalAreaName : "Vietnam" },
          { GlobalArea_Id : "52", GlobalAreaName : "Yemen" },
          { GlobalArea_Id : "53", GlobalAreaName : "Hong Kong" },
          { GlobalArea_Id : "54", GlobalAreaName : "Macau" },
          { GlobalArea_Id : "56", GlobalAreaName : "Albania" },
          { GlobalArea_Id : "57", GlobalAreaName : "Andorra" },
          { GlobalArea_Id : "58", GlobalAreaName : "Austria" },
          { GlobalArea_Id : "59", GlobalAreaName : "Belarus" },
          { GlobalArea_Id : "60", GlobalAreaName : "Belgium" },
          { GlobalArea_Id : "61", GlobalAreaName : "Bosnia and Herzegovina" },
          { GlobalArea_Id : "62", GlobalAreaName : "Bulgaria" },
          { GlobalArea_Id : "63", GlobalAreaName : "Croatia" },
          { GlobalArea_Id : "64", GlobalAreaName : "Czech Republic" },
          { GlobalArea_Id : "65", GlobalAreaName : "Denmark" },
          { GlobalArea_Id : "66", GlobalAreaName : "Estonia" },
          { GlobalArea_Id : "67", GlobalAreaName : "Finland" },
          { GlobalArea_Id : "68", GlobalAreaName : "France" },
          { GlobalArea_Id : "69", GlobalAreaName : "Germany" },
          { GlobalArea_Id : "70", GlobalAreaName : "Greece" },
          { GlobalArea_Id : "71", GlobalAreaName : "Hungary" },
          { GlobalArea_Id : "72", GlobalAreaName : "Iceland" },
          { GlobalArea_Id : "73", GlobalAreaName : "Ireland" },
          { GlobalArea_Id : "74", GlobalAreaName : "Italy" },
          { GlobalArea_Id : "75", GlobalAreaName : "Latvia" },
          { GlobalArea_Id : "76", GlobalAreaName : "Liechtenstein" },
          { GlobalArea_Id : "77", GlobalAreaName : "Lithuania" },
          { GlobalArea_Id : "78", GlobalAreaName : "Luxembourg" },
          { GlobalArea_Id : "79", GlobalAreaName : "Macedonia" },
          { GlobalArea_Id : "80", GlobalAreaName : "Malta" },
          { GlobalArea_Id : "81", GlobalAreaName : "Moldova" },
          { GlobalArea_Id : "82", GlobalAreaName : "Monaco" },
          { GlobalArea_Id : "83", GlobalAreaName : "Montenegro" },
          { GlobalArea_Id : "84", GlobalAreaName : "Netherlands" },
          { GlobalArea_Id : "85", GlobalAreaName : "Norway" },
          { GlobalArea_Id : "86", GlobalAreaName : "Poland" },
          { GlobalArea_Id : "87", GlobalAreaName : "Portugal" },
          { GlobalArea_Id : "88", GlobalAreaName : "Romania" },
          { GlobalArea_Id : "89", GlobalAreaName : "Russian Federation" },
          { GlobalArea_Id : "90", GlobalAreaName : "San Marino" },
          { GlobalArea_Id : "91", GlobalAreaName : "Serbia" },
          { GlobalArea_Id : "92", GlobalAreaName : "Slovakia" },
          { GlobalArea_Id : "93", GlobalAreaName : "Slovenia" },
          { GlobalArea_Id : "94", GlobalAreaName : "Spain" },
          { GlobalArea_Id : "95", GlobalAreaName : "Sweden" },
          { GlobalArea_Id : "96", GlobalAreaName : "Switzerland" },
          { GlobalArea_Id : "97", GlobalAreaName : "Ukraine" },
          { GlobalArea_Id : "98", GlobalAreaName : "United Kingdom" },
          { GlobalArea_Id : "99", GlobalAreaName : "Vatican" },
          { GlobalArea_Id : "100", GlobalAreaName : "Antigua and Barbuda" },
          { GlobalArea_Id : "101", GlobalAreaName : "Bahamas" },
          { GlobalArea_Id : "102", GlobalAreaName : "Barbados" },
          { GlobalArea_Id : "103", GlobalAreaName : "Belize" },
          { GlobalArea_Id : "104", GlobalAreaName : "Canada" },
          { GlobalArea_Id : "105", GlobalAreaName : "Costa Rica" },
          { GlobalArea_Id : "106", GlobalAreaName : "Cuba" },
          { GlobalArea_Id : "108", GlobalAreaName : "Dominican Republic" },
          { GlobalArea_Id : "109", GlobalAreaName : "El Salvador" },
          { GlobalArea_Id : "110", GlobalAreaName : "Grenada" },
          { GlobalArea_Id : "111", GlobalAreaName : "Guatemala" },
          { GlobalArea_Id : "112", GlobalAreaName : "Haiti" },
          { GlobalArea_Id : "113", GlobalAreaName : "Honduras" },
          { GlobalArea_Id : "114", GlobalAreaName : "Jamaica" },
          { GlobalArea_Id : "115", GlobalAreaName : "Mexico" },
          { GlobalArea_Id : "116", GlobalAreaName : "Nicaragua" },
          { GlobalArea_Id : "117", GlobalAreaName : "Panama" },
          { GlobalArea_Id : "119", GlobalAreaName : "Saint Lucia" },
          { GlobalArea_Id : "121", GlobalAreaName : "Trinidad and Tobago" },
          { GlobalArea_Id : "122", GlobalAreaName : "United States" },
          { GlobalArea_Id : "123", GlobalAreaName : "Argentina" },
          { GlobalArea_Id : "124", GlobalAreaName : "Bolivia" },
          { GlobalArea_Id : "125", GlobalAreaName : "Brazil" },
          { GlobalArea_Id : "126", GlobalAreaName : "Chile" },
          { GlobalArea_Id : "127", GlobalAreaName : "Colombia" },
          { GlobalArea_Id : "128", GlobalAreaName : "Ecuador" },
          { GlobalArea_Id : "129", GlobalAreaName : "Guyana" },
          { GlobalArea_Id : "130", GlobalAreaName : "Paraguay" },
          { GlobalArea_Id : "131", GlobalAreaName : "Peru" },
          { GlobalArea_Id : "132", GlobalAreaName : "Suriname" },
          { GlobalArea_Id : "133", GlobalAreaName : "Uruguay" },
          { GlobalArea_Id : "134", GlobalAreaName : "Venezuela" },
          { GlobalArea_Id : "135", GlobalAreaName : "Australia" },
          { GlobalArea_Id : "136", GlobalAreaName : "Fiji" },
          { GlobalArea_Id : "137", GlobalAreaName : "Kiribati" },
          { GlobalArea_Id : "138", GlobalAreaName : "Marshall Islands" },
          { GlobalArea_Id : "139", GlobalAreaName : "Micronesia" },
          { GlobalArea_Id : "140", GlobalAreaName : "Nauru" },
          { GlobalArea_Id : "141", GlobalAreaName : "New Zealand" },
          { GlobalArea_Id : "143", GlobalAreaName : "Papua New Guinea" },
          { GlobalArea_Id : "146", GlobalAreaName : "Tonga" },
          { GlobalArea_Id : "147", GlobalAreaName : "Tuvalu" },
          { GlobalArea_Id : "148", GlobalAreaName : "Vanuatu" },
          { GlobalArea_Id : "150", GlobalAreaName : "Algeria" },
          { GlobalArea_Id : "151", GlobalAreaName : "Angola" },
          { GlobalArea_Id : "153", GlobalAreaName : "Benin" },
          { GlobalArea_Id : "154", GlobalAreaName : "Botswana" },
          { GlobalArea_Id : "155", GlobalAreaName : "Burkina Faso" },
          { GlobalArea_Id : "156", GlobalAreaName : "Burundi" },
          { GlobalArea_Id : "157", GlobalAreaName : "Cameroon" },
          { GlobalArea_Id : "158", GlobalAreaName : "Cape Verde" },
          { GlobalArea_Id : "159", GlobalAreaName : "Central African Republic" },
          { GlobalArea_Id : "160", GlobalAreaName : "Chad" },
          { GlobalArea_Id : "161", GlobalAreaName : "Comoros" },
          { GlobalArea_Id : "162", GlobalAreaName : "Congo" },
          { GlobalArea_Id : "163", GlobalAreaName : "Republic of the Congo" },
          { GlobalArea_Id : "165", GlobalAreaName : "Djibouti" },
          { GlobalArea_Id : "166", GlobalAreaName : "Egypt" },
          { GlobalArea_Id : "167", GlobalAreaName : "Equatorial Guinea" },
          { GlobalArea_Id : "168", GlobalAreaName : "Eritrea" },
          { GlobalArea_Id : "169", GlobalAreaName : "Ethiopia" },
          { GlobalArea_Id : "170", GlobalAreaName : "Gabon" },
          { GlobalArea_Id : "171", GlobalAreaName : "Gambia" },
          { GlobalArea_Id : "172", GlobalAreaName : "Ghana" },
          { GlobalArea_Id : "173", GlobalAreaName : "Guinea" },
          { GlobalArea_Id : "174", GlobalAreaName : "Guinea-Bissau" },
          { GlobalArea_Id : "175", GlobalAreaName : "Kenya" },
          { GlobalArea_Id : "176", GlobalAreaName : "Lesotho" },
          { GlobalArea_Id : "177", GlobalAreaName : "Liberia" },
          { GlobalArea_Id : "178", GlobalAreaName : "Libya" },
          { GlobalArea_Id : "179", GlobalAreaName : "Madagascar" },
          { GlobalArea_Id : "180", GlobalAreaName : "Malawi" },
          { GlobalArea_Id : "181", GlobalAreaName : "Mali" },
          { GlobalArea_Id : "182", GlobalAreaName : "Mauritania" },
          { GlobalArea_Id : "183", GlobalAreaName : "Mauritius" },
          { GlobalArea_Id : "184", GlobalAreaName : "Morocco" },
          { GlobalArea_Id : "185", GlobalAreaName : "Mozambique" },
          { GlobalArea_Id : "186", GlobalAreaName : "Namibia" },
          { GlobalArea_Id : "187", GlobalAreaName : "Niger" },
          { GlobalArea_Id : "188", GlobalAreaName : "Nigeria" },
          { GlobalArea_Id : "189", GlobalAreaName : "Rwanda" },
          { GlobalArea_Id : "191", GlobalAreaName : "Senegal" },
          { GlobalArea_Id : "192", GlobalAreaName : "Seychelles" },
          { GlobalArea_Id : "193", GlobalAreaName : "Sierra Leone" },
          { GlobalArea_Id : "194", GlobalAreaName : "Somalia" },
          { GlobalArea_Id : "195", GlobalAreaName : "South Africa" },
          { GlobalArea_Id : "196", GlobalAreaName : "Sudan" },
          { GlobalArea_Id : "197", GlobalAreaName : "Swaziland" },
          { GlobalArea_Id : "198", GlobalAreaName : "Tanzania" },
          { GlobalArea_Id : "199", GlobalAreaName : "Togo" },
          { GlobalArea_Id : "200", GlobalAreaName : "Tunisia" },
          { GlobalArea_Id : "201", GlobalAreaName : "Uganda" },
          { GlobalArea_Id : "202", GlobalAreaName : "Zambia" },
          { GlobalArea_Id : "203", GlobalAreaName : "Zimbabwe" },
          { GlobalArea_Id : "316", GlobalAreaName : "Puerto Rico" },
          { GlobalArea_Id : "317", GlobalAreaName : "Cyprus" },
          { GlobalArea_Id : "320", GlobalAreaName : "Faroe Islands" },
          { GlobalArea_Id : "321", GlobalAreaName : "New Caledonia" },
          { GlobalArea_Id : "322", GlobalAreaName : "French Polynesia" },
          { GlobalArea_Id : "323", GlobalAreaName : "Martinique" },
          { GlobalArea_Id : "324", GlobalAreaName : "Guadeloupe" },
          { GlobalArea_Id : "325", GlobalAreaName : "Gibraltar" },
          { GlobalArea_Id : "326", GlobalAreaName : "Reunion" },
          { GlobalArea_Id : "327", GlobalAreaName : "Palestine" },
          { GlobalArea_Id : "328", GlobalAreaName : "Aruba" },
          { GlobalArea_Id : "329", GlobalAreaName : "其他" },
          { GlobalArea_Id : "330", GlobalAreaName : "Yugoslavia" },
          { GlobalArea_Id : "331", GlobalAreaName : "欧洲联盟" }
     ];
})(window);
