(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_387 = { Name: "索尼 Z1 Mini", Product: [
                                        { ProductId: "3060", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01001.jpg"},
                                        { ProductId: "3061", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01002.jpg"},
                                        { ProductId: "3062", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01003.jpg"},
                                        { ProductId: "3063", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01004.jpg"},
                                        { ProductId: "3064", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01005.jpg"},
                                        { ProductId: "3065", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01006.jpg"},
                                        { ProductId: "3066", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01007.jpg"},
                                        { ProductId: "3067", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01008.jpg"},
                                        { ProductId: "3068", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01009.jpg"},
                                        { ProductId: "3069", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01010.jpg"},
                                        { ProductId: "3070", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01011.jpg"},
                                        { ProductId: "3071", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01012.jpg"},
                                        { ProductId: "3072", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01013.jpg"},
                                        { ProductId: "3073", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01014.jpg"},
                                        { ProductId: "3074", PdcId: "387", ProdName: "Painted Leather Case For Sony Xperia Z1 Mini - [PLC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000706/01015.jpg"},
                                        { ProductId: "4233", PdcId: "387", ProdName: "Frosted Matte Plastic Hard For Sony Xperia Z1 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000270/G270_00006.jpg"},
                                        { ProductId: "4234", PdcId: "387", ProdName: "Leaf Leather Case For Sony Xperia Z1 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000533/G533_00005.JPG"}
                                        ] };
})(window);
