(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_347 = { Name: "三星 S4 Mini", Product: [
                                        { ProductId: "2267", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01001.jpg"},
                                        { ProductId: "2268", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01002.jpg"},
                                        { ProductId: "2269", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01003.jpg"},
                                        { ProductId: "2270", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01004.jpg"},
                                        { ProductId: "2271", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01005.jpg"},
                                        { ProductId: "2272", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01006.jpg"},
                                        { ProductId: "2273", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01007.jpg"},
                                        { ProductId: "2274", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01008.jpg"},
                                        { ProductId: "2275", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01009.jpg"},
                                        { ProductId: "2276", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01010.jpg"},
                                        { ProductId: "2277", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01011.jpg"},
                                        { ProductId: "2278", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01012.jpg"},
                                        { ProductId: "2279", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01013.jpg"},
                                        { ProductId: "2280", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01014.jpg"},
                                        { ProductId: "2281", PdcId: "347", ProdName: "Painted Soft Case For Samsung Galaxy S4 Mini - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPTTPU01/01/01015.jpg"},
                                        { ProductId: "2282", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01001.jpg"},
                                        { ProductId: "2283", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01002.jpg"},
                                        { ProductId: "2284", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01003.jpg"},
                                        { ProductId: "2285", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01004.jpg"},
                                        { ProductId: "2286", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01005.jpg"},
                                        { ProductId: "2287", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01006.jpg"},
                                        { ProductId: "2288", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01007.jpg"},
                                        { ProductId: "2289", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01008.jpg"},
                                        { ProductId: "2290", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01009.jpg"},
                                        { ProductId: "2291", PdcId: "347", ProdName: "Painted Leather Case For Samsung Galaxy S4 Mini - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIPLT02/01010.jpg"},
                                        { ProductId: "4166", PdcId: "347", ProdName: "Frosted Matte Plastic Hard For Samsung Galaxy S4 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000498/G498_00005.jpg"},
                                        { ProductId: "4167", PdcId: "347", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy S4 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000240/G240_00005.jpg"},
                                        { ProductId: "4168", PdcId: "347", ProdName: "Leather Case For Samsung Galaxy S4 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000373/G373_00003.jpg"},
                                        { ProductId: "4169", PdcId: "347", ProdName: "Leaf Leather Case For Samsung Galaxy S4 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4MINIBL01/01/01005.jpg"}
                                        ] };
})(window);
