(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_367 = { Name: "三星 Ace 4", Product: [
                                        { ProductId: "4023", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01001.jpg"},
                                        { ProductId: "4024", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01002.jpg"},
                                        { ProductId: "4025", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01003.jpg"},
                                        { ProductId: "4026", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01004.jpg"},
                                        { ProductId: "4027", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01005.jpg"},
                                        { ProductId: "4028", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01006.jpg"},
                                        { ProductId: "4029", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01007.jpg"},
                                        { ProductId: "4030", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01008.jpg"},
                                        { ProductId: "4031", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01009.jpg"},
                                        { ProductId: "4032", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01010.jpg"},
                                        { ProductId: "4033", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01011.jpg"},
                                        { ProductId: "4034", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01012.jpg"},
                                        { ProductId: "4035", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01013.jpg"},
                                        { ProductId: "4036", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01014.jpg"},
                                        { ProductId: "4037", PdcId: "367", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4PTTPU01/01/01015.jpg"},
                                        { ProductId: "4038", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01001.jpg"},
                                        { ProductId: "4039", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01002.jpg"},
                                        { ProductId: "4040", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01003.jpg"},
                                        { ProductId: "4041", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01004.jpg"},
                                        { ProductId: "4042", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01005.jpg"},
                                        { ProductId: "4043", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01006.jpg"},
                                        { ProductId: "4044", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01007.jpg"},
                                        { ProductId: "4045", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01008.jpg"},
                                        { ProductId: "4046", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01009.jpg"},
                                        { ProductId: "4047", PdcId: "367", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG313PLT02/01010.jpg"}
                                        ] };
})(window);
