(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_359 = { Name: "三星 E5", Product: [
                                        { ProductId: "3736", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01001.jpg"},
                                        { ProductId: "3737", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01002.jpg"},
                                        { ProductId: "3738", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01003.jpg"},
                                        { ProductId: "3739", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01004.jpg"},
                                        { ProductId: "3740", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01005.jpg"},
                                        { ProductId: "3741", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01006.jpg"},
                                        { ProductId: "3742", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01007.jpg"},
                                        { ProductId: "3743", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01008.jpg"},
                                        { ProductId: "3744", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01009.jpg"},
                                        { ProductId: "3745", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01010.jpg"},
                                        { ProductId: "3746", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01011.jpg"},
                                        { ProductId: "3747", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01012.jpg"},
                                        { ProductId: "3748", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01013.jpg"},
                                        { ProductId: "3749", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01014.jpg"},
                                        { ProductId: "3750", PdcId: "359", ProdName: "Painted Soft Case For Samsung Galaxy E5 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PTTPU01/01/01015.jpg"},
                                        { ProductId: "3751", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01001.jpg"},
                                        { ProductId: "3752", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01002.jpg"},
                                        { ProductId: "3753", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01003.jpg"},
                                        { ProductId: "3754", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01004.jpg"},
                                        { ProductId: "3755", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01005.jpg"},
                                        { ProductId: "3756", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01006.jpg"},
                                        { ProductId: "3757", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01007.jpg"},
                                        { ProductId: "3758", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01008.jpg"},
                                        { ProductId: "3759", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01009.jpg"},
                                        { ProductId: "3760", PdcId: "359", ProdName: "Painted Leather Case For Samsung Galaxy E5 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5PLT02/01010.jpg"},
                                        { ProductId: "4331", PdcId: "359", ProdName: "Leaf Leather Case For Samsung Galaxy E5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGE5BL01/01/01005.jpg"}
                                        ] };
})(window);
