(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_360 = { Name: "三星 J7", Product: [
                                        { ProductId: "3761", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01001.jpg"},
                                        { ProductId: "3762", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01002.jpg"},
                                        { ProductId: "3763", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01003.jpg"},
                                        { ProductId: "3764", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01004.jpg"},
                                        { ProductId: "3765", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01005.jpg"},
                                        { ProductId: "3766", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01006.jpg"},
                                        { ProductId: "3767", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01007.jpg"},
                                        { ProductId: "3768", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01008.jpg"},
                                        { ProductId: "3769", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01009.jpg"},
                                        { ProductId: "3770", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01010.jpg"},
                                        { ProductId: "3771", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01011.jpg"},
                                        { ProductId: "3772", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01012.jpg"},
                                        { ProductId: "3773", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01013.jpg"},
                                        { ProductId: "3774", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01014.jpg"},
                                        { ProductId: "3775", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01015.jpg"},
                                        { ProductId: "3776", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01016.jpg"},
                                        { ProductId: "3777", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01017.jpg"},
                                        { ProductId: "3778", PdcId: "360", ProdName: "Painted Soft Case For Samsung Galaxy J7 - [PCSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PTTPU01/01/01018.jpg"},
                                        { ProductId: "3779", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01001.jpg"},
                                        { ProductId: "3780", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01002.jpg"},
                                        { ProductId: "3781", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01003.jpg"},
                                        { ProductId: "3782", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01004.jpg"},
                                        { ProductId: "3783", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01005.jpg"},
                                        { ProductId: "3784", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01006.jpg"},
                                        { ProductId: "3785", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01007.jpg"},
                                        { ProductId: "3786", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01008.jpg"},
                                        { ProductId: "3787", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01009.jpg"},
                                        { ProductId: "3788", PdcId: "360", ProdName: "Painted Leather Case For Samsung Galaxy J7 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ7PLT02/01010.jpg"}
                                        ] };
})(window);
