(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_368 = { Name: "三星 Ace 4 Lite", Product: [
                                        { ProductId: "4048", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01001.jpg"},
                                        { ProductId: "4049", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01002.jpg"},
                                        { ProductId: "4050", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01003.jpg"},
                                        { ProductId: "4051", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01004.jpg"},
                                        { ProductId: "4052", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01005.jpg"},
                                        { ProductId: "4053", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01006.jpg"},
                                        { ProductId: "4054", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01007.jpg"},
                                        { ProductId: "4055", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01008.jpg"},
                                        { ProductId: "4056", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01009.jpg"},
                                        { ProductId: "4057", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01010.jpg"},
                                        { ProductId: "4058", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01011.jpg"},
                                        { ProductId: "4059", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01012.jpg"},
                                        { ProductId: "4060", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01013.jpg"},
                                        { ProductId: "4061", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01014.jpg"},
                                        { ProductId: "4062", PdcId: "368", ProdName: "Painted Soft Case For Samsung Galaxy Ace 4 Lite - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGACE4LITEPTTPU01/01/01015.jpg"},
                                        { ProductId: "4063", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01001.jpg"},
                                        { ProductId: "4064", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01002.jpg"},
                                        { ProductId: "4065", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01003.jpg"},
                                        { ProductId: "4066", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01004.jpg"},
                                        { ProductId: "4067", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01005.jpg"},
                                        { ProductId: "4068", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01006.jpg"},
                                        { ProductId: "4069", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01007.jpg"},
                                        { ProductId: "4070", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01008.jpg"},
                                        { ProductId: "4071", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01009.jpg"},
                                        { ProductId: "4072", PdcId: "368", ProdName: "Painted Leather Case For Samsung Galaxy Ace 4 Lite - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG357PLT02/01010.jpg"}
                                        ] };
})(window);
