(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_371 = { Name: "三星 Tab A", Product: [
                                        { ProductId: "4108", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01001.jpg"},
                                        { ProductId: "4109", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01002.jpg"},
                                        { ProductId: "4110", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01003.jpg"},
                                        { ProductId: "4111", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01004.jpg"},
                                        { ProductId: "4112", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01005.jpg"},
                                        { ProductId: "4113", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01006.jpg"},
                                        { ProductId: "4114", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T350 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT350PICC01/01/01007.jpg"},
                                        { ProductId: "4115", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01001.jpg"},
                                        { ProductId: "4116", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01002.jpg"},
                                        { ProductId: "4117", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01003.jpg"},
                                        { ProductId: "4118", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01004.jpg"},
                                        { ProductId: "4119", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01005.jpg"},
                                        { ProductId: "4120", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01006.jpg"},
                                        { ProductId: "4121", PdcId: "371", ProdName: "Painted Leather Case For Samsung Galaxy Tab A T550 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT550PICC01/01/01007.jpg"}
                                        ] };
})(window);
