(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_354 = { Name: "三星 Note Edge", Product: [
                                        { ProductId: "2569", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01001.jpg"},
                                        { ProductId: "2570", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01002.jpg"},
                                        { ProductId: "2571", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01003.jpg"},
                                        { ProductId: "2572", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01004.jpg"},
                                        { ProductId: "2573", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01005.jpg"},
                                        { ProductId: "2574", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01006.jpg"},
                                        { ProductId: "2575", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01007.jpg"},
                                        { ProductId: "2576", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01008.jpg"},
                                        { ProductId: "2577", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01009.jpg"},
                                        { ProductId: "2578", PdcId: "354", ProdName: "Painted Leather Case For Samsung Galaxy Note Edge - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEPLT02/01010.jpg"},
                                        { ProductId: "4181", PdcId: "354", ProdName: "Leaf Leather Case For Samsung Galaxy Note Edge", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTEEDGEBL01/01/01005.jpg"}
                                        ] };
})(window);
