(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_366 = { Name: "三星 S7562", Product: [
                                        { ProductId: "3973", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01001.jpg"},
                                        { ProductId: "3974", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01002.jpg"},
                                        { ProductId: "3975", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01003.jpg"},
                                        { ProductId: "3976", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01004.jpg"},
                                        { ProductId: "3977", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01005.jpg"},
                                        { ProductId: "3978", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01006.jpg"},
                                        { ProductId: "3979", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01007.jpg"},
                                        { ProductId: "3980", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01008.jpg"},
                                        { ProductId: "3981", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01009.jpg"},
                                        { ProductId: "3982", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01010.jpg"},
                                        { ProductId: "3983", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01011.jpg"},
                                        { ProductId: "3984", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01012.jpg"},
                                        { ProductId: "3985", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01013.jpg"},
                                        { ProductId: "3986", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01014.jpg"},
                                        { ProductId: "3987", PdcId: "366", ProdName: "Painted Soft Case For Samsung Galaxy Trend Duos S7562 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562PTTPU01/01/01015.jpg"},
                                        { ProductId: "4337", PdcId: "366", ProdName: "Leaf Leather Case For Samsung Galaxy S7562", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS7562BL01/01/01005.jpg"}
                                        ] };
})(window);
