(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_392 = { Name: "索尼 M5", Product: [
                                        { ProductId: "3143", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01001.jpg"},
                                        { ProductId: "3144", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01002.jpg"},
                                        { ProductId: "3145", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01003.jpg"},
                                        { ProductId: "3146", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01004.jpg"},
                                        { ProductId: "3147", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01005.jpg"},
                                        { ProductId: "3148", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01006.jpg"},
                                        { ProductId: "3149", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01007.jpg"},
                                        { ProductId: "3150", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01008.jpg"},
                                        { ProductId: "3151", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01009.jpg"},
                                        { ProductId: "3152", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01010.jpg"},
                                        { ProductId: "3153", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01011.jpg"},
                                        { ProductId: "3154", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01012.jpg"},
                                        { ProductId: "3155", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01013.jpg"},
                                        { ProductId: "3156", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01014.jpg"},
                                        { ProductId: "3157", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01015.jpg"},
                                        { ProductId: "3158", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01016.jpg"},
                                        { ProductId: "3159", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01017.jpg"},
                                        { ProductId: "3160", PdcId: "392", ProdName: "Painted Soft Case For Sony Xperia M5 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM5PTTPU01/01/01018.jpg"}
                                        ] };
})(window);
