(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_462 = { Name: "华硕 2", Product: [
                                        { ProductId: "3895", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01001.jpg"},
                                        { ProductId: "3896", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01002.jpg"},
                                        { ProductId: "3897", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01003.jpg"},
                                        { ProductId: "3898", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01004.jpg"},
                                        { ProductId: "3899", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01005.jpg"},
                                        { ProductId: "3900", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01006.jpg"},
                                        { ProductId: "3901", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01007.jpg"},
                                        { ProductId: "3902", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01008.jpg"},
                                        { ProductId: "3903", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01009.jpg"},
                                        { ProductId: "3904", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01010.jpg"},
                                        { ProductId: "3905", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01011.jpg"},
                                        { ProductId: "3906", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01012.jpg"},
                                        { ProductId: "3907", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01013.jpg"},
                                        { ProductId: "3908", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01014.jpg"},
                                        { ProductId: "3909", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01015.jpg"},
                                        { ProductId: "3910", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01016.jpg"},
                                        { ProductId: "3911", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01017.jpg"},
                                        { ProductId: "3912", PdcId: "462", ProdName: "Painted Soft Case For Asus Zenfone 2 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PTTPU01/01/01018.jpg"},
                                        { ProductId: "3913", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01001.jpg"},
                                        { ProductId: "3914", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01002.jpg"},
                                        { ProductId: "3915", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01003.jpg"},
                                        { ProductId: "3916", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01004.jpg"},
                                        { ProductId: "3917", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01005.jpg"},
                                        { ProductId: "3918", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01006.jpg"},
                                        { ProductId: "3919", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01007.jpg"},
                                        { ProductId: "3920", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01008.jpg"},
                                        { ProductId: "3921", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01009.jpg"},
                                        { ProductId: "3922", PdcId: "462", ProdName: "Painted Leather Case For Asus Zenfone 2 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2PLT02/01010.jpg"},
                                        { ProductId: "4334", PdcId: "462", ProdName: "Leaf Leather Case For Asus Zenfone 2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS2BL01/01/01005.jpg"}
                                        ] };
})(window);
