(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_370 = { Name: "三星 Tab 3", Product: [
                                        { ProductId: "4094", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01001.jpg"},
                                        { ProductId: "4095", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01002.jpg"},
                                        { ProductId: "4096", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01003.jpg"},
                                        { ProductId: "4097", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01004.jpg"},
                                        { ProductId: "4098", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01005.jpg"},
                                        { ProductId: "4099", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01006.jpg"},
                                        { ProductId: "4100", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T110 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT110PICC01/01/01007.jpg"},
                                        { ProductId: "4101", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01001.jpg"},
                                        { ProductId: "4102", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01002.jpg"},
                                        { ProductId: "4103", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01003.jpg"},
                                        { ProductId: "4104", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01004.jpg"},
                                        { ProductId: "4105", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01005.jpg"},
                                        { ProductId: "4106", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01006.jpg"},
                                        { ProductId: "4107", PdcId: "370", ProdName: "Painted Leather Case For Samsung Galaxy Tab 3 T310 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT310PICC01/01/01007.jpg"}
                                        ] };
})(window);
