(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_401 = { Name: "华为 P7", Product: [
                                        { ProductId: "3288", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00001.jpg"},
                                        { ProductId: "3289", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00002.jpg"},
                                        { ProductId: "3290", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00003.jpg"},
                                        { ProductId: "3291", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00004.jpg"},
                                        { ProductId: "3292", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00005.jpg"},
                                        { ProductId: "3293", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00006.jpg"},
                                        { ProductId: "3294", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00007.jpg"},
                                        { ProductId: "3295", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00008.jpg"},
                                        { ProductId: "3296", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00009.jpg"},
                                        { ProductId: "3297", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00010.jpg"},
                                        { ProductId: "3300", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00013.jpg"},
                                        { ProductId: "3301", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00014.jpg"},
                                        { ProductId: "3302", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00015.jpg"},
                                        { ProductId: "3303", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00016.jpg"},
                                        { ProductId: "3305", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00018.jpg"},
                                        { ProductId: "3306", PdcId: "401", ProdName: "Painted Soft Case For Huawei Ascend P7 - [PSC0019]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00019.jpg"},
                                        { ProductId: "4252", PdcId: "401", ProdName: "Ultra Thin Transparent Soft TPU Case For Huawei Ascend G7", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000210/G210_00006.jpg"}
                                        ] };
})(window);
