(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_428 = { Name: "诺基亚 640", Product: [
                                        { ProductId: "3358", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01001.jpg"},
                                        { ProductId: "3359", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01002.jpg"},
                                        { ProductId: "3360", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01003.jpg"},
                                        { ProductId: "3361", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01004.jpg"},
                                        { ProductId: "3362", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01005.jpg"},
                                        { ProductId: "3363", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01006.jpg"},
                                        { ProductId: "3364", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01007.jpg"},
                                        { ProductId: "3365", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01008.jpg"},
                                        { ProductId: "3366", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01009.jpg"},
                                        { ProductId: "3367", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01010.jpg"},
                                        { ProductId: "3368", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01011.jpg"},
                                        { ProductId: "3369", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01012.jpg"},
                                        { ProductId: "3370", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01013.jpg"},
                                        { ProductId: "3371", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01014.jpg"},
                                        { ProductId: "3372", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01015.jpg"},
                                        { ProductId: "3373", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01016.jpg"},
                                        { ProductId: "3374", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01017.jpg"},
                                        { ProductId: "3375", PdcId: "428", ProdName: "Painted Soft Case For Nokia Lumia 640 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PTTPU01/01/01018.jpg"},
                                        { ProductId: "3376", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01001.jpg"},
                                        { ProductId: "3377", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01002.jpg"},
                                        { ProductId: "3378", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01003.jpg"},
                                        { ProductId: "3379", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01004.jpg"},
                                        { ProductId: "3380", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01005.jpg"},
                                        { ProductId: "3381", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01006.jpg"},
                                        { ProductId: "3382", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01007.jpg"},
                                        { ProductId: "3383", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01008.jpg"},
                                        { ProductId: "3384", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01009.jpg"},
                                        { ProductId: "3385", PdcId: "428", ProdName: "Painted Leather Case For Nokia Lumia 640 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640PLT02/01010.jpg"},
                                        { ProductId: "4274", PdcId: "428", ProdName: "Leaf Leather Case For Nokia Lumia 640", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA640BL01/01/01005.jpg"}
                                        ] };
})(window);
