(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_369 = { Name: "三星 Tab 4", Product: [
                                        { ProductId: "4073", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01001.jpg"},
                                        { ProductId: "4074", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01002.jpg"},
                                        { ProductId: "4075", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01003.jpg"},
                                        { ProductId: "4076", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01004.jpg"},
                                        { ProductId: "4077", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01005.jpg"},
                                        { ProductId: "4078", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01006.jpg"},
                                        { ProductId: "4079", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T230 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT230PICC01/01/01007.jpg"},
                                        { ProductId: "4080", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01001.jpg"},
                                        { ProductId: "4081", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01002.jpg"},
                                        { ProductId: "4082", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01003.jpg"},
                                        { ProductId: "4083", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01004.jpg"},
                                        { ProductId: "4084", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01005.jpg"},
                                        { ProductId: "4085", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01006.jpg"},
                                        { ProductId: "4086", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T330 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT330PICC01/01/01007.jpg"},
                                        { ProductId: "4087", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01001.jpg"},
                                        { ProductId: "4088", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01002.jpg"},
                                        { ProductId: "4089", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01003.jpg"},
                                        { ProductId: "4090", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01004.jpg"},
                                        { ProductId: "4091", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01005.jpg"},
                                        { ProductId: "4092", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01006.jpg"},
                                        { ProductId: "4093", PdcId: "369", ProdName: "Painted Leather Case For Samsung Galaxy Tab 4 T530 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT530PICC01/01/01007.jpg"}
                                        ] };
})(window);
