(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_351 = { Name: "三星 Note 5 Edge", Product: [
                                        { ProductId: "2380", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01001.jpg"},
                                        { ProductId: "2381", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01002.jpg"},
                                        { ProductId: "2382", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01003.jpg"},
                                        { ProductId: "2383", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01004.jpg"},
                                        { ProductId: "2384", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01005.jpg"},
                                        { ProductId: "2385", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01006.jpg"},
                                        { ProductId: "2386", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01007.jpg"},
                                        { ProductId: "2387", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01008.jpg"},
                                        { ProductId: "2388", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01009.jpg"},
                                        { ProductId: "2389", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01010.jpg"},
                                        { ProductId: "2390", PdcId: "351", ProdName: "Painted Leather Case For Samsung Galaxy Note 5 Edge - [PLC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGNOTE5EDGEPLT02/01011.jpg"}
                                        ] };
})(window);
