(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_438 = { Name: "摩托罗拉 G3", Product: [
                                        { ProductId: "3464", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01001.jpg"},
                                        { ProductId: "3465", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01002.jpg"},
                                        { ProductId: "3466", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01003.jpg"},
                                        { ProductId: "3467", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01004.jpg"},
                                        { ProductId: "3468", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01005.jpg"},
                                        { ProductId: "3469", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01006.jpg"},
                                        { ProductId: "3470", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01007.jpg"},
                                        { ProductId: "3471", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01008.jpg"},
                                        { ProductId: "3472", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01009.jpg"},
                                        { ProductId: "3473", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01010.jpg"},
                                        { ProductId: "3474", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01011.jpg"},
                                        { ProductId: "3475", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01012.jpg"},
                                        { ProductId: "3476", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01013.jpg"},
                                        { ProductId: "3477", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01014.jpg"},
                                        { ProductId: "3478", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01015.jpg"},
                                        { ProductId: "3479", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01016.jpg"},
                                        { ProductId: "3480", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01017.jpg"},
                                        { ProductId: "3481", PdcId: "438", ProdName: "Painted Soft Case For Motorola Moto G3 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PTTPU01/01/01018.jpg"},
                                        { ProductId: "3482", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01001.jpg"},
                                        { ProductId: "3483", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01002.jpg"},
                                        { ProductId: "3484", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01003.jpg"},
                                        { ProductId: "3485", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01004.jpg"},
                                        { ProductId: "3486", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01005.jpg"},
                                        { ProductId: "3487", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01006.jpg"},
                                        { ProductId: "3488", PdcId: "438", ProdName: "Painted Leather Case For Motorola Moto G3 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG3PLT02/01007.jpg"}
                                        ] };
})(window);
