(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_361 = { Name: "三星 J5", Product: [
                                        { ProductId: "3789", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01001.jpg"},
                                        { ProductId: "3790", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01002.jpg"},
                                        { ProductId: "3791", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01003.jpg"},
                                        { ProductId: "3792", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01004.jpg"},
                                        { ProductId: "3793", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01005.jpg"},
                                        { ProductId: "3794", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01006.jpg"},
                                        { ProductId: "3795", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01007.jpg"},
                                        { ProductId: "3796", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01008.jpg"},
                                        { ProductId: "3797", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01009.jpg"},
                                        { ProductId: "3798", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01010.jpg"},
                                        { ProductId: "3799", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01011.jpg"},
                                        { ProductId: "3800", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01012.jpg"},
                                        { ProductId: "3801", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01013.jpg"},
                                        { ProductId: "3802", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01014.jpg"},
                                        { ProductId: "3803", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01015.jpg"},
                                        { ProductId: "3804", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01016.jpg"},
                                        { ProductId: "3805", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01017.jpg"},
                                        { ProductId: "3806", PdcId: "361", ProdName: "Painted Soft Case For Samsung Galaxy J5 - [PCSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PTTPU01/01/01018.jpg"},
                                        { ProductId: "3807", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01001.jpg"},
                                        { ProductId: "3808", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01002.jpg"},
                                        { ProductId: "3809", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01003.jpg"},
                                        { ProductId: "3810", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01004.jpg"},
                                        { ProductId: "3811", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01005.jpg"},
                                        { ProductId: "3812", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01006.jpg"},
                                        { ProductId: "3813", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01007.jpg"},
                                        { ProductId: "3814", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01008.jpg"},
                                        { ProductId: "3815", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01009.jpg"},
                                        { ProductId: "3816", PdcId: "361", ProdName: "Painted Leather Case For Samsung Galaxy J5 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ5PLT02/01010.jpg"}
                                        ] };
})(window);
