(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_345 = { Name: "三星 S5 Mini", Product: [
                                        { ProductId: "2217", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01001.jpg"},
                                        { ProductId: "2218", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01002.jpg"},
                                        { ProductId: "2219", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01003.jpg"},
                                        { ProductId: "2220", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01004.jpg"},
                                        { ProductId: "2221", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01005.jpg"},
                                        { ProductId: "2222", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01006.jpg"},
                                        { ProductId: "2223", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01007.jpg"},
                                        { ProductId: "2224", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01008.jpg"},
                                        { ProductId: "2225", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01009.jpg"},
                                        { ProductId: "2226", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01010.jpg"},
                                        { ProductId: "2227", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01011.jpg"},
                                        { ProductId: "2228", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01012.jpg"},
                                        { ProductId: "2229", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01013.jpg"},
                                        { ProductId: "2230", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01014.jpg"},
                                        { ProductId: "2231", PdcId: "345", ProdName: "Painted Soft Case For Samsung Galaxy S5 Mini - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPTTPU01/01/01015.jpg"},
                                        { ProductId: "2232", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01001.jpg"},
                                        { ProductId: "2233", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01002.jpg"},
                                        { ProductId: "2234", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01003.jpg"},
                                        { ProductId: "2235", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01004.jpg"},
                                        { ProductId: "2236", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01005.jpg"},
                                        { ProductId: "2237", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01006.jpg"},
                                        { ProductId: "2238", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01007.jpg"},
                                        { ProductId: "2239", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01008.jpg"},
                                        { ProductId: "2240", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01009.jpg"},
                                        { ProductId: "2241", PdcId: "345", ProdName: "Painted Leather Case For Samsung Galaxy S5 Mini - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIPLT02/01010.jpg"},
                                        { ProductId: "4159", PdcId: "345", ProdName: "Frosted Matte Plastic Hard For Samsung Galaxy S5 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000497/G497_00006.jpg"},
                                        { ProductId: "4160", PdcId: "345", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy S5 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000239/G239_00004.jpg"},
                                        { ProductId: "4161", PdcId: "345", ProdName: "Leather Case For Samsung Galaxy S5 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000375/G375_00003.jpg"},
                                        { ProductId: "4162", PdcId: "345", ProdName: "Leaf Leather Case For Samsung Galaxy S5 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5MINIBL01/01/01005.jpg"}
                                        ] };
})(window);
