(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_357 = { Name: "三星 Grand Prime", Product: [
                                        { ProductId: "2632", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01001.jpg"},
                                        { ProductId: "2633", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01002.jpg"},
                                        { ProductId: "2634", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01003.jpg"},
                                        { ProductId: "2635", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01004.jpg"},
                                        { ProductId: "2636", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01005.jpg"},
                                        { ProductId: "2637", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01006.jpg"},
                                        { ProductId: "2638", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01007.jpg"},
                                        { ProductId: "2639", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01008.jpg"},
                                        { ProductId: "2640", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01009.jpg"},
                                        { ProductId: "2641", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01010.jpg"},
                                        { ProductId: "2642", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01011.jpg"},
                                        { ProductId: "2643", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01012.jpg"},
                                        { ProductId: "2644", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01013.jpg"},
                                        { ProductId: "2645", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01014.jpg"},
                                        { ProductId: "2646", PdcId: "357", ProdName: "Painted Soft Case For Samsung Galaxy Grand Prime - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PTTPU01/01/01015.jpg"},
                                        { ProductId: "2647", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01001.jpg"},
                                        { ProductId: "2648", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01002.jpg"},
                                        { ProductId: "2649", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01003.jpg"},
                                        { ProductId: "2650", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01004.jpg"},
                                        { ProductId: "2651", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01005.jpg"},
                                        { ProductId: "2652", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01006.jpg"},
                                        { ProductId: "2653", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01007.jpg"},
                                        { ProductId: "2654", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01008.jpg"},
                                        { ProductId: "2655", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01009.jpg"},
                                        { ProductId: "2656", PdcId: "357", ProdName: "Painted Leather Case For Samsung Galaxy Grand Prime - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530PLT02/01010.jpg"},
                                        { ProductId: "4187", PdcId: "357", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy Grand Prime", Price: "$0", Currency: "USD", Url: "", MainPic: ""},
                                        { ProductId: "4188", PdcId: "357", ProdName: "Leaf Leather Case For Samsung Galaxy Grand Prime", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG530BL01/01/01005.jpg"}
                                        ] };
})(window);
