(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_439 = { Name: "摩托罗拉 G2", Product: [
                                        { ProductId: "3489", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01001.jpg"},
                                        { ProductId: "3490", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01002.jpg"},
                                        { ProductId: "3491", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01003.jpg"},
                                        { ProductId: "3492", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01004.jpg"},
                                        { ProductId: "3493", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01005.jpg"},
                                        { ProductId: "3494", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01006.jpg"},
                                        { ProductId: "3495", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01007.jpg"},
                                        { ProductId: "3496", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01008.jpg"},
                                        { ProductId: "3497", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01009.jpg"},
                                        { ProductId: "3498", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01010.jpg"},
                                        { ProductId: "3499", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01011.jpg"},
                                        { ProductId: "3500", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01012.jpg"},
                                        { ProductId: "3501", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01013.jpg"},
                                        { ProductId: "3502", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01014.jpg"},
                                        { ProductId: "3503", PdcId: "439", ProdName: "Painted Soft Case For Motorola Moto G2 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PTTPU01/01/01015.jpg"},
                                        { ProductId: "3504", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01001.jpg"},
                                        { ProductId: "3505", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01002.jpg"},
                                        { ProductId: "3506", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01003.jpg"},
                                        { ProductId: "3507", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01004.jpg"},
                                        { ProductId: "3508", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01005.jpg"},
                                        { ProductId: "3509", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01006.jpg"},
                                        { ProductId: "3510", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01007.jpg"},
                                        { ProductId: "3511", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01008.jpg"},
                                        { ProductId: "3512", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01009.jpg"},
                                        { ProductId: "3513", PdcId: "439", ProdName: "Painted Leather Case For Motorola Moto G2 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2PLT02/01010.jpg"},
                                        { ProductId: "4287", PdcId: "439", ProdName: "Frosted Matte Plastic Hard For Motorola Moto G2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000296/G296_00005.jpg"},
                                        { ProductId: "4288", PdcId: "439", ProdName: "Shockproof Protection Case For Motorola Moto G2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000353/G353_00005.jpg"},
                                        { ProductId: "4289", PdcId: "439", ProdName: "Leaf Leather Case For Motorola Moto G2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/MOTOG2BL01/01/01005.jpg"}
                                        ] };
})(window);
