(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_408 = { Name: "华为 Mate 7", Product: [
                                        { ProductId: "3328", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00001.jpg"},
                                        { ProductId: "3329", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00002.jpg"},
                                        { ProductId: "3330", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00003.jpg"},
                                        { ProductId: "3331", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00004.jpg"},
                                        { ProductId: "3332", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00005.jpg"},
                                        { ProductId: "3333", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00006.jpg"},
                                        { ProductId: "3334", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00007.jpg"},
                                        { ProductId: "3335", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00008.jpg"},
                                        { ProductId: "3336", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00009.jpg"},
                                        { ProductId: "3337", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00010.jpg"},
                                        { ProductId: "3338", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00011.jpg"},
                                        { ProductId: "3339", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00012.jpg"},
                                        { ProductId: "3340", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00013.jpg"},
                                        { ProductId: "3341", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00014.jpg"},
                                        { ProductId: "3342", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00015.jpg"},
                                        { ProductId: "3343", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00016.jpg"},
                                        { ProductId: "3344", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00017.jpg"},
                                        { ProductId: "3345", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00018.jpg"},
                                        { ProductId: "3346", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0019]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00019.jpg"},
                                        { ProductId: "3347", PdcId: "408", ProdName: "Painted Soft Case For Huawei Ascend Mate 7 - [PSC0020]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000452/G452_00020.jpg"},
                                        { ProductId: "4258", PdcId: "408", ProdName: "Ultra Thin Transparent Soft TPU Case For Huawei Ascend Mate 7", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000233/G233_00005.jpg"}
                                        ] };
})(window);
