(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_362 = { Name: "三星 J1", Product: [
                                        { ProductId: "3817", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01001.jpg"},
                                        { ProductId: "3818", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01002.jpg"},
                                        { ProductId: "3819", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01003.jpg"},
                                        { ProductId: "3820", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01004.jpg"},
                                        { ProductId: "3821", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01005.jpg"},
                                        { ProductId: "3822", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01006.jpg"},
                                        { ProductId: "3823", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01007.jpg"},
                                        { ProductId: "3824", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01008.jpg"},
                                        { ProductId: "3825", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01009.jpg"},
                                        { ProductId: "3826", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01010.jpg"},
                                        { ProductId: "3827", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01011.jpg"},
                                        { ProductId: "3828", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01012.jpg"},
                                        { ProductId: "3829", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01013.jpg"},
                                        { ProductId: "3830", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01014.jpg"},
                                        { ProductId: "3831", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01015.jpg"},
                                        { ProductId: "3832", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01016.jpg"},
                                        { ProductId: "3833", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01017.jpg"},
                                        { ProductId: "3834", PdcId: "362", ProdName: "Painted Soft Case For Samsung Galaxy J1 - [PCSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PTTPU01/01/01018.jpg"},
                                        { ProductId: "3835", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01001.jpg"},
                                        { ProductId: "3836", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01002.jpg"},
                                        { ProductId: "3837", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01003.jpg"},
                                        { ProductId: "3838", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01004.jpg"},
                                        { ProductId: "3839", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01005.jpg"},
                                        { ProductId: "3840", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01006.jpg"},
                                        { ProductId: "3841", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01007.jpg"},
                                        { ProductId: "3842", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01008.jpg"},
                                        { ProductId: "3843", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01009.jpg"},
                                        { ProductId: "3844", PdcId: "362", ProdName: "Painted Leather Case For Samsung Galaxy J1 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGJ1PLT02/01010.jpg"}
                                        ] };
})(window);
