(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_384 = { Name: "索尼 Z2", Product: [
                                        { ProductId: "3035", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01001.jpg"},
                                        { ProductId: "3036", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01002.jpg"},
                                        { ProductId: "3037", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01003.jpg"},
                                        { ProductId: "3038", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01004.jpg"},
                                        { ProductId: "3039", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01005.jpg"},
                                        { ProductId: "3040", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01006.jpg"},
                                        { ProductId: "3041", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01007.jpg"},
                                        { ProductId: "3042", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01008.jpg"},
                                        { ProductId: "3043", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01009.jpg"},
                                        { ProductId: "3044", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01010.jpg"},
                                        { ProductId: "3045", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01011.jpg"},
                                        { ProductId: "3046", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01012.jpg"},
                                        { ProductId: "3047", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01013.jpg"},
                                        { ProductId: "3048", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01014.jpg"},
                                        { ProductId: "3049", PdcId: "384", ProdName: "Painted Soft Case For Sony Xperia Z2 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PTTPU01/01/01015.jpg"},
                                        { ProductId: "3050", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01001.jpg"},
                                        { ProductId: "3051", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01002.jpg"},
                                        { ProductId: "3052", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01003.jpg"},
                                        { ProductId: "3053", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01004.jpg"},
                                        { ProductId: "3054", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01005.jpg"},
                                        { ProductId: "3055", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01006.jpg"},
                                        { ProductId: "3056", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01007.jpg"},
                                        { ProductId: "3057", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01008.jpg"},
                                        { ProductId: "3058", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01009.jpg"},
                                        { ProductId: "3059", PdcId: "384", ProdName: "Painted Leather Case For Sony Xperia Z2 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2PLT02/01010.jpg"},
                                        { ProductId: "4225", PdcId: "384", ProdName: "Frosted Matte Plastic Hard For Sony Xperia Z2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000267/G267_00006.jpg"},
                                        { ProductId: "4226", PdcId: "384", ProdName: "Shockproof Protection Case For Sony Xperia Z2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000347/G347_00004.jpg"},
                                        { ProductId: "4227", PdcId: "384", ProdName: "Leather Case For Sony Xperia Z2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000381/G381_00003.jpg"},
                                        { ProductId: "4228", PdcId: "384", ProdName: "Leaf Leather Case For Sony Xperia Z2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYZ2BL01/01/01005.jpg"}
                                        ] };
})(window);
