(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_331 = { Name: "iPhone 4", Product: [
                                        { ProductId: "3948", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01001.jpg"},
                                        { ProductId: "3949", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01002.jpg"},
                                        { ProductId: "3950", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01003.jpg"},
                                        { ProductId: "3951", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01004.jpg"},
                                        { ProductId: "3952", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01005.jpg"},
                                        { ProductId: "3953", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01006.jpg"},
                                        { ProductId: "3954", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01007.jpg"},
                                        { ProductId: "3955", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01008.jpg"},
                                        { ProductId: "3956", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01009.jpg"},
                                        { ProductId: "3957", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01010.jpg"},
                                        { ProductId: "3958", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01011.jpg"},
                                        { ProductId: "3959", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01012.jpg"},
                                        { ProductId: "3960", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01013.jpg"},
                                        { ProductId: "3961", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01014.jpg"},
                                        { ProductId: "3962", PdcId: "331", ProdName: "Painted Soft Case For iPhone 4 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PTTPU01/01/01015.jpg"},
                                        { ProductId: "3963", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01001.jpg"},
                                        { ProductId: "3964", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01002.jpg"},
                                        { ProductId: "3965", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01003.jpg"},
                                        { ProductId: "3966", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01004.jpg"},
                                        { ProductId: "3967", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01005.jpg"},
                                        { ProductId: "3968", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01006.jpg"},
                                        { ProductId: "3969", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01007.jpg"},
                                        { ProductId: "3970", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01008.jpg"},
                                        { ProductId: "3971", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01009.jpg"},
                                        { ProductId: "3972", PdcId: "331", ProdName: "Painted Leather Case For iPhone 4 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4PLT02/01010.jpg"},
                                        { ProductId: "4336", PdcId: "331", ProdName: "Leaf Leather Case For iPhone 4", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE4BL01/01/01005.jpg"}
                                        ] };
})(window);
