(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_419 = { Name: "红米 2", Product: [
                                        { ProductId: "3650", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01001.jpg"},
                                        { ProductId: "3651", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01002.jpg"},
                                        { ProductId: "3652", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01003.jpg"},
                                        { ProductId: "3653", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01004.jpg"},
                                        { ProductId: "3654", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01005.jpg"},
                                        { ProductId: "3655", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01006.jpg"},
                                        { ProductId: "3656", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01007.jpg"},
                                        { ProductId: "3657", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01008.jpg"},
                                        { ProductId: "3658", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01009.jpg"},
                                        { ProductId: "3659", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01010.jpg"},
                                        { ProductId: "3660", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01011.jpg"},
                                        { ProductId: "3661", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01012.jpg"},
                                        { ProductId: "3662", PdcId: "419", ProdName: "Painted Soft Case For Xiaomi Redmi 2 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000707/01013.jpg"},
                                        { ProductId: "4322", PdcId: "419", ProdName: "Ultra Thin Transparent Soft TPU Case For Xiaomi Redmi 2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000251/G251_00003.jpg"}
                                        ] };
})(window);
