(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_356 = { Name: "三星 Grand 2", Product: [
                                        { ProductId: "2607", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01001.jpg"},
                                        { ProductId: "2608", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01002.jpg"},
                                        { ProductId: "2609", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01003.jpg"},
                                        { ProductId: "2610", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01004.jpg"},
                                        { ProductId: "2611", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01005.jpg"},
                                        { ProductId: "2612", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01006.jpg"},
                                        { ProductId: "2613", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01007.jpg"},
                                        { ProductId: "2614", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01008.jpg"},
                                        { ProductId: "2615", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01009.jpg"},
                                        { ProductId: "2616", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01010.jpg"},
                                        { ProductId: "2617", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01011.jpg"},
                                        { ProductId: "2618", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01012.jpg"},
                                        { ProductId: "2619", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01013.jpg"},
                                        { ProductId: "2620", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01014.jpg"},
                                        { ProductId: "2621", PdcId: "356", ProdName: "Painted Soft Case For Samsung Galaxy Grand 2 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PTTPU01/01/01015.jpg"},
                                        { ProductId: "2622", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01001.jpg"},
                                        { ProductId: "2623", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01002.jpg"},
                                        { ProductId: "2624", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01003.jpg"},
                                        { ProductId: "2625", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01004.jpg"},
                                        { ProductId: "2626", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01005.jpg"},
                                        { ProductId: "2627", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01006.jpg"},
                                        { ProductId: "2628", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01007.jpg"},
                                        { ProductId: "2629", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01008.jpg"},
                                        { ProductId: "2630", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01009.jpg"},
                                        { ProductId: "2631", PdcId: "356", ProdName: "Painted Leather Case For Samsung Galaxy Grand 2 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG7106PLT02/01010.jpg"},
                                        { ProductId: "4186", PdcId: "356", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy Grand 2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000247/G247_00005.jpg"}
                                        ] };
})(window);
