(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_430 = { Name: "诺基亚 630", Product: [
                                        { ProductId: "3396", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01001.jpg"},
                                        { ProductId: "3397", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01002.jpg"},
                                        { ProductId: "3398", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01003.jpg"},
                                        { ProductId: "3399", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01004.jpg"},
                                        { ProductId: "3400", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01005.jpg"},
                                        { ProductId: "3401", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01006.jpg"},
                                        { ProductId: "3402", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01007.jpg"},
                                        { ProductId: "3403", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01008.jpg"},
                                        { ProductId: "3404", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01009.jpg"},
                                        { ProductId: "3405", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01010.jpg"},
                                        { ProductId: "3406", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01011.jpg"},
                                        { ProductId: "3407", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01012.jpg"},
                                        { ProductId: "3408", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01013.jpg"},
                                        { ProductId: "3409", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01014.jpg"},
                                        { ProductId: "3410", PdcId: "430", ProdName: "Painted Soft Case For Nokia Lumia 630 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PTTPU01/01/01015.jpg"},
                                        { ProductId: "3411", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01001.jpg"},
                                        { ProductId: "3412", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01002.jpg"},
                                        { ProductId: "3413", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01003.jpg"},
                                        { ProductId: "3414", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01004.jpg"},
                                        { ProductId: "3415", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01005.jpg"},
                                        { ProductId: "3416", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01006.jpg"},
                                        { ProductId: "3417", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01007.jpg"},
                                        { ProductId: "3418", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01008.jpg"},
                                        { ProductId: "3419", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01009.jpg"},
                                        { ProductId: "3420", PdcId: "430", ProdName: "Painted Leather Case For Nokia Lumia 630 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630PLT02/01010.jpg"},
                                        { ProductId: "4275", PdcId: "430", ProdName: "Frosted Matte Plastic Hard For Nokia Lumia 630", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000304/G304_00006.jpg"},
                                        { ProductId: "4276", PdcId: "430", ProdName: "Leaf Leather Case For Nokia Lumia 630", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA630BL01/01/01005.jpg"}
                                        ] };
})(window);
