(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_432 = { Name: "诺基亚 535", Product: [
                                        { ProductId: "3421", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01001.jpg"},
                                        { ProductId: "3422", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01002.jpg"},
                                        { ProductId: "3423", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01003.jpg"},
                                        { ProductId: "3424", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01004.jpg"},
                                        { ProductId: "3425", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01005.jpg"},
                                        { ProductId: "3426", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01006.jpg"},
                                        { ProductId: "3427", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01007.jpg"},
                                        { ProductId: "3428", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01008.jpg"},
                                        { ProductId: "3429", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01009.jpg"},
                                        { ProductId: "3430", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01010.jpg"},
                                        { ProductId: "3431", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01011.jpg"},
                                        { ProductId: "3432", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01012.jpg"},
                                        { ProductId: "3433", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01013.jpg"},
                                        { ProductId: "3434", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01014.jpg"},
                                        { ProductId: "3435", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01015.jpg"},
                                        { ProductId: "3436", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01016.jpg"},
                                        { ProductId: "3437", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01017.jpg"},
                                        { ProductId: "3438", PdcId: "432", ProdName: "Painted Soft Case For Nokia Lumia 535 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535PTTPU01/01/01018.jpg"},
                                        { ProductId: "4278", PdcId: "432", ProdName: "Leaf Leather Case For Nokia Lumia 535", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA535BL01/01/01005.jpg"}
                                        ] };
})(window);
