(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_329 = { Name: "iPhone 5", Product: [
                                        { ProductId: "1703", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01001.jpg"},
                                        { ProductId: "1704", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01002.jpg"},
                                        { ProductId: "1705", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01003.jpg"},
                                        { ProductId: "1706", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01004.jpg"},
                                        { ProductId: "1707", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01005.jpg"},
                                        { ProductId: "1708", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01006.jpg"},
                                        { ProductId: "1709", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01007.jpg"},
                                        { ProductId: "1710", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01008.jpg"},
                                        { ProductId: "1711", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01009.jpg"},
                                        { ProductId: "1712", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01010.jpg"},
                                        { ProductId: "1713", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01011.jpg"},
                                        { ProductId: "1714", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01012.jpg"},
                                        { ProductId: "1715", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01013.jpg"},
                                        { ProductId: "1716", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01014.jpg"},
                                        { ProductId: "1717", PdcId: "329", ProdName: "Painted Soft Case For iPhone 5 / 5s - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PTTPU01/01/01015.jpg"},
                                        { ProductId: "1718", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01001.jpg"},
                                        { ProductId: "1719", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01002.jpg"},
                                        { ProductId: "1720", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01003.jpg"},
                                        { ProductId: "1721", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01004.jpg"},
                                        { ProductId: "1722", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01005.jpg"},
                                        { ProductId: "1723", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01006.jpg"},
                                        { ProductId: "1724", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01007.jpg"},
                                        { ProductId: "1725", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01008.jpg"},
                                        { ProductId: "1726", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01009.jpg"},
                                        { ProductId: "1727", PdcId: "329", ProdName: "Painted Leather Case For iPhone 5 / 5s - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5PLT02/01010.jpg"},
                                        { ProductId: "4144", PdcId: "329", ProdName: "Leaf Leather Case For iPhone 5 / 5s", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5BL01/01/01004.jpg"}
                                        ] };
})(window);
