(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_330 = { Name: "iPhone 5c", Product: [
                                        { ProductId: "3923", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01001.jpg"},
                                        { ProductId: "3924", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01002.jpg"},
                                        { ProductId: "3925", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01003.jpg"},
                                        { ProductId: "3926", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01004.jpg"},
                                        { ProductId: "3927", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01005.jpg"},
                                        { ProductId: "3928", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01006.jpg"},
                                        { ProductId: "3929", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01007.jpg"},
                                        { ProductId: "3930", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01008.jpg"},
                                        { ProductId: "3931", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01009.jpg"},
                                        { ProductId: "3932", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01010.jpg"},
                                        { ProductId: "3933", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01011.jpg"},
                                        { ProductId: "3934", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01012.jpg"},
                                        { ProductId: "3935", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01013.jpg"},
                                        { ProductId: "3936", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01014.jpg"},
                                        { ProductId: "3937", PdcId: "330", ProdName: "Painted Soft Case For iPhone 5C - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPTTPU01/01/01015.jpg"},
                                        { ProductId: "3938", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01001.jpg"},
                                        { ProductId: "3939", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01002.jpg"},
                                        { ProductId: "3940", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01003.jpg"},
                                        { ProductId: "3941", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01004.jpg"},
                                        { ProductId: "3942", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01005.jpg"},
                                        { ProductId: "3943", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01006.jpg"},
                                        { ProductId: "3944", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01007.jpg"},
                                        { ProductId: "3945", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01008.jpg"},
                                        { ProductId: "3946", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01009.jpg"},
                                        { ProductId: "3947", PdcId: "330", ProdName: "Painted Leather Case For iPhone 5C - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5CPLT02/01010.jpg"},
                                        { ProductId: "4335", PdcId: "330", ProdName: "Leaf Leather Case For iPhone 5C", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/IPHONE5BL01/01/01005.jpg"}
                                        ] };
})(window);
