(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_394 = { Name: "索尼 C3", Product: [
                                        { ProductId: "3161", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00001.jpg"},
                                        { ProductId: "3162", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00002.jpg"},
                                        { ProductId: "3163", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00003.jpg"},
                                        { ProductId: "3164", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00004.jpg"},
                                        { ProductId: "3165", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00005.jpg"},
                                        { ProductId: "3166", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00006.jpg"},
                                        { ProductId: "3167", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00007.jpg"},
                                        { ProductId: "3168", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00008.jpg"},
                                        { ProductId: "3169", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00009.jpg"},
                                        { ProductId: "3170", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00010.jpg"},
                                        { ProductId: "3171", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00011.jpg"},
                                        { ProductId: "3172", PdcId: "394", ProdName: "Painted Hard Case For Sony Xperia C3 - [PHC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000539/G539_00012.jpg"},
                                        { ProductId: "4240", PdcId: "394", ProdName: "Frosted Matte Plastic Hard For Sony Xperia C3", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000277/G277_00005.jpg"},
                                        { ProductId: "4241", PdcId: "394", ProdName: "Leaf Leather Case For Sony Xperia C3", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000538/G538_00005.jpg"}
                                        ] };
})(window);
