(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_377 = { Name: "LG G2 Mini", Product: [
                                        { ProductId: "2797", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01001.jpg"},
                                        { ProductId: "2798", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01002.jpg"},
                                        { ProductId: "2799", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01003.jpg"},
                                        { ProductId: "2800", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01004.jpg"},
                                        { ProductId: "2801", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01005.jpg"},
                                        { ProductId: "2802", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01006.jpg"},
                                        { ProductId: "2803", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01007.jpg"},
                                        { ProductId: "2804", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01008.jpg"},
                                        { ProductId: "2805", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01009.jpg"},
                                        { ProductId: "2806", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01010.jpg"},
                                        { ProductId: "2807", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01011.jpg"},
                                        { ProductId: "2808", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01012.jpg"},
                                        { ProductId: "2809", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01013.jpg"},
                                        { ProductId: "2810", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01014.jpg"},
                                        { ProductId: "2811", PdcId: "377", ProdName: "Painted Soft Case For LG G2 Mini - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPTTPU01/01/01015.jpg"},
                                        { ProductId: "2812", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01001.jpg"},
                                        { ProductId: "2813", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0019]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01002.jpg"},
                                        { ProductId: "2814", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0020]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01003.jpg"},
                                        { ProductId: "2815", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0021]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01004.jpg"},
                                        { ProductId: "2816", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0022]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01005.jpg"},
                                        { ProductId: "2817", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0023]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01006.jpg"},
                                        { ProductId: "2818", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0024]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01007.jpg"},
                                        { ProductId: "2819", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0025]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01008.jpg"},
                                        { ProductId: "2820", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0026]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01009.jpg"},
                                        { ProductId: "2821", PdcId: "377", ProdName: "Painted Leather Case For LG G2 Mini - [PLC0027]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/LGG2MINIPLT02/01010.jpg"},
                                        { ProductId: "4204", PdcId: "377", ProdName: "Ultra Thin Transparent Soft TPU Case For LG G2 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000255/G255_00003.jpg"},
                                        { ProductId: "4205", PdcId: "377", ProdName: "Leaf Leather Case For LG G2 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000527C/G527_00004.JPG"}
                                        ] };
})(window);
