(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_364 = { Name: "三星 Core 2", Product: [
                                        { ProductId: "3845", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01001.jpg"},
                                        { ProductId: "3846", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01002.jpg"},
                                        { ProductId: "3847", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01003.jpg"},
                                        { ProductId: "3848", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01004.jpg"},
                                        { ProductId: "3849", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01005.jpg"},
                                        { ProductId: "3850", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01006.jpg"},
                                        { ProductId: "3851", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01007.jpg"},
                                        { ProductId: "3852", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01008.jpg"},
                                        { ProductId: "3853", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01009.jpg"},
                                        { ProductId: "3854", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01010.jpg"},
                                        { ProductId: "3855", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01011.jpg"},
                                        { ProductId: "3856", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01012.jpg"},
                                        { ProductId: "3857", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01013.jpg"},
                                        { ProductId: "3858", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01014.jpg"},
                                        { ProductId: "3859", PdcId: "364", ProdName: "Painted Soft Case For Samsung Galaxy Core 2 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PTTPU01/01/01015.jpg"},
                                        { ProductId: "3860", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01001.jpg"},
                                        { ProductId: "3861", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01002.jpg"},
                                        { ProductId: "3862", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01003.jpg"},
                                        { ProductId: "3863", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01004.jpg"},
                                        { ProductId: "3864", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01005.jpg"},
                                        { ProductId: "3865", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01006.jpg"},
                                        { ProductId: "3866", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01007.jpg"},
                                        { ProductId: "3867", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01008.jpg"},
                                        { ProductId: "3868", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01009.jpg"},
                                        { ProductId: "3869", PdcId: "364", ProdName: "Painted Leather Case For Samsung Galaxy Core 2 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355PLT02/01010.jpg"},
                                        { ProductId: "4332", PdcId: "364", ProdName: "Leaf Leather Case For Samsung Galaxy Core 2", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG355HBL01/01/01005.jpg"}
                                        ] };
})(window);
