(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_344 = { Name: "三星 S5", Product: [
                                        { ProductId: "2192", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01001.jpg"},
                                        { ProductId: "2193", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01002.jpg"},
                                        { ProductId: "2194", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01003.jpg"},
                                        { ProductId: "2195", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01004.jpg"},
                                        { ProductId: "2196", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01005.jpg"},
                                        { ProductId: "2197", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01006.jpg"},
                                        { ProductId: "2198", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01007.jpg"},
                                        { ProductId: "2199", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01008.jpg"},
                                        { ProductId: "2200", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01009.jpg"},
                                        { ProductId: "2201", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01010.jpg"},
                                        { ProductId: "2202", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01011.jpg"},
                                        { ProductId: "2203", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01012.jpg"},
                                        { ProductId: "2204", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01013.jpg"},
                                        { ProductId: "2205", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01014.jpg"},
                                        { ProductId: "2206", PdcId: "344", ProdName: "Painted Soft Case For Samsung Galaxy S5 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PTTPU01/01/01015.jpg"},
                                        { ProductId: "2207", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01001.jpg"},
                                        { ProductId: "2208", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01002.jpg"},
                                        { ProductId: "2209", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01003.jpg"},
                                        { ProductId: "2210", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01004.jpg"},
                                        { ProductId: "2211", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01005.jpg"},
                                        { ProductId: "2212", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01006.jpg"},
                                        { ProductId: "2213", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01007.jpg"},
                                        { ProductId: "2214", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01008.jpg"},
                                        { ProductId: "2215", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01009.jpg"},
                                        { ProductId: "2216", PdcId: "344", ProdName: "Painted Leather Case For Samsung Galaxy S5 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS5PLT02/01010.jpg"},
                                        { ProductId: "4155", PdcId: "344", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy S5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000236/G236_00004.jpg"},
                                        { ProductId: "4156", PdcId: "344", ProdName: "Leather Case For Samsung Galaxy S5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000374/G374_00003.jpg"},
                                        { ProductId: "4157", PdcId: "344", ProdName: "Leaf Leather Case For Samsung Galaxy S5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000556/G556_00005.JPG"},
                                        { ProductId: "4158", PdcId: "344", ProdName: "Frosted Matte Plastic Hard For Samsung Galaxy S5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000497/G497_00006.jpg"}
                                        ] };
})(window);
