(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_433 = { Name: "诺基亚 530", Product: [
                                        { ProductId: "3439", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01001.jpg"},
                                        { ProductId: "3440", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01002.jpg"},
                                        { ProductId: "3441", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01003.jpg"},
                                        { ProductId: "3442", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01004.jpg"},
                                        { ProductId: "3443", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01005.jpg"},
                                        { ProductId: "3444", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01006.jpg"},
                                        { ProductId: "3445", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01007.jpg"},
                                        { ProductId: "3446", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01008.jpg"},
                                        { ProductId: "3447", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01009.jpg"},
                                        { ProductId: "3448", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01010.jpg"},
                                        { ProductId: "3449", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01011.jpg"},
                                        { ProductId: "3450", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01012.jpg"},
                                        { ProductId: "3451", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01013.jpg"},
                                        { ProductId: "3452", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01014.jpg"},
                                        { ProductId: "3453", PdcId: "433", ProdName: "Painted Soft Case For Nokia Lumia 530 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PTTPU01/01/01015.jpg"},
                                        { ProductId: "3454", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01001.jpg"},
                                        { ProductId: "3455", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01002.jpg"},
                                        { ProductId: "3456", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01003.jpg"},
                                        { ProductId: "3457", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01004.jpg"},
                                        { ProductId: "3458", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01005.jpg"},
                                        { ProductId: "3459", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01006.jpg"},
                                        { ProductId: "3460", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01007.jpg"},
                                        { ProductId: "3461", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01008.jpg"},
                                        { ProductId: "3462", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01009.jpg"},
                                        { ProductId: "3463", PdcId: "433", ProdName: "Painted Leather Case For Nokia Lumia 530 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530PLT02/01010.jpg"},
                                        { ProductId: "4279", PdcId: "433", ProdName: "Frosted Matte Plastic Hard For Nokia Lumia 530", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000306/G306_00006.jpg"},
                                        { ProductId: "4280", PdcId: "433", ProdName: "Shockproof Protection Case For Nokia Lumia 530", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000357/G357_00005.jpg"},
                                        { ProductId: "4281", PdcId: "433", ProdName: "Leaf Leather Case For Nokia Lumia 530", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/NOKIA530BL01/01/01005.jpg"}
                                        ] };
})(window);
