(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_400 = { Name: "华为 P8", Product: [
                                        { ProductId: "3268", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00001.jpg"},
                                        { ProductId: "3269", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00002.jpg"},
                                        { ProductId: "3270", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00003.jpg"},
                                        { ProductId: "3271", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00004.jpg"},
                                        { ProductId: "3272", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00005.jpg"},
                                        { ProductId: "3273", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00006.jpg"},
                                        { ProductId: "3274", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00007.jpg"},
                                        { ProductId: "3275", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00008.jpg"},
                                        { ProductId: "3276", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00009.jpg"},
                                        { ProductId: "3277", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00010.jpg"},
                                        { ProductId: "3278", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00011.jpg"},
                                        { ProductId: "3279", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00012.jpg"},
                                        { ProductId: "3280", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00013.jpg"},
                                        { ProductId: "3281", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00014.jpg"},
                                        { ProductId: "3282", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00015.jpg"},
                                        { ProductId: "3283", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00016.jpg"},
                                        { ProductId: "3284", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00017.jpg"},
                                        { ProductId: "3285", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00018.jpg"},
                                        { ProductId: "3286", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0019]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00019.jpg"},
                                        { ProductId: "3287", PdcId: "400", ProdName: "Painted Soft Case For Huawei Ascend P8 - [PSC0020]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000450/G450_00020.jpg"},
                                        { ProductId: "4250", PdcId: "400", ProdName: "Ultra Thin Transparent Soft TPU Case For Huawei Ascend P8", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000508/G508_00003.jpg"},
                                        { ProductId: "4251", PdcId: "400", ProdName: "Leaf Leather Case For Huawei Ascend P8", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/HUAWEIP8BL01/01/01005.jpg"}
                                        ] };
})(window);
