(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_388 = { Name: "索尼 Z-Ultra", Product: [
                                        { ProductId: "3075", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00001.jpg"},
                                        { ProductId: "3076", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00002.jpg"},
                                        { ProductId: "3077", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00003.jpg"},
                                        { ProductId: "3078", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00004.jpg"},
                                        { ProductId: "3079", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00005.jpg"},
                                        { ProductId: "3080", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00006.jpg"},
                                        { ProductId: "3081", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00007.jpg"},
                                        { ProductId: "3082", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00008.jpg"},
                                        { ProductId: "3083", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00009.jpg"},
                                        { ProductId: "3084", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00010.jpg"},
                                        { ProductId: "3085", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00011.jpg"},
                                        { ProductId: "3086", PdcId: "388", ProdName: "Painted Hard Case For Sony Xperia Z Ultra XL39h - [PHC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000534/G534_00012.jpg"},
                                        { ProductId: "4235", PdcId: "388", ProdName: "Frosted Matte Plastic Hard For Sony Xperia Z Ultra", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000276/G276_00003.jpg"}
                                        ] };
})(window);
