(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_339 = { Name: "三星 S6 Edge Plus", Product: [
                                        { ProductId: "1914", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01001.jpg"},
                                        { ProductId: "1915", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01002.jpg"},
                                        { ProductId: "1916", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01003.jpg"},
                                        { ProductId: "1917", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01004.jpg"},
                                        { ProductId: "1918", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01005.jpg"},
                                        { ProductId: "1919", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01006.jpg"},
                                        { ProductId: "1920", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01007.jpg"},
                                        { ProductId: "1921", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01008.jpg"},
                                        { ProductId: "1922", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01009.jpg"},
                                        { ProductId: "1923", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01010.jpg"},
                                        { ProductId: "1924", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01011.jpg"},
                                        { ProductId: "1925", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01012.jpg"},
                                        { ProductId: "1926", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01013.jpg"},
                                        { ProductId: "1927", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01014.jpg"},
                                        { ProductId: "1928", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01015.jpg"},
                                        { ProductId: "1929", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01016.jpg"},
                                        { ProductId: "1930", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01017.jpg"},
                                        { ProductId: "1931", PdcId: "339", ProdName: "Painted Soft Case For Samsung Galaxy S6 Edge Plus - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EPLUSPTTPU01/01/01018.jpg"},
                                        { ProductId: "4149", PdcId: "339", ProdName: "Leaf Leather Case For Samsung Galaxy S6 Edge Plus", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS6EDGEPLUSBL01/01/01005.jpg"}
                                        ] };
})(window);
