(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_346 = { Name: "三星 S4", Product: [
                                        { ProductId: "2242", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01001.jpg"},
                                        { ProductId: "2243", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01002.jpg"},
                                        { ProductId: "2244", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01003.jpg"},
                                        { ProductId: "2245", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01004.jpg"},
                                        { ProductId: "2246", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01005.jpg"},
                                        { ProductId: "2247", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01006.jpg"},
                                        { ProductId: "2248", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01007.jpg"},
                                        { ProductId: "2249", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01008.jpg"},
                                        { ProductId: "2250", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01009.jpg"},
                                        { ProductId: "2251", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01010.jpg"},
                                        { ProductId: "2252", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01011.jpg"},
                                        { ProductId: "2253", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01012.jpg"},
                                        { ProductId: "2254", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01013.jpg"},
                                        { ProductId: "2255", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01014.jpg"},
                                        { ProductId: "2256", PdcId: "346", ProdName: "Painted Soft Case For Samsung Galaxy S4 - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PTTPU01/01/01015.jpg"},
                                        { ProductId: "2257", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01001.jpg"},
                                        { ProductId: "2258", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01002.jpg"},
                                        { ProductId: "2259", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01003.jpg"},
                                        { ProductId: "2260", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01004.jpg"},
                                        { ProductId: "2261", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01005.jpg"},
                                        { ProductId: "2262", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01006.jpg"},
                                        { ProductId: "2263", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01007.jpg"},
                                        { ProductId: "2264", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01008.jpg"},
                                        { ProductId: "2265", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01009.jpg"},
                                        { ProductId: "2266", PdcId: "346", ProdName: "Painted Leather Case For Samsung Galaxy S4 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4PLT02/01010.jpg"},
                                        { ProductId: "4163", PdcId: "346", ProdName: "Ultra Thin Transparent Soft TPU Case For Samsung Galaxy S4", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000237/G237_00005.jpg"},
                                        { ProductId: "4164", PdcId: "346", ProdName: "Leather Case For Samsung Galaxy S4", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000372/G372_00003.jpg"},
                                        { ProductId: "4165", PdcId: "346", ProdName: "Leaf Leather Case For Samsung Galaxy S4", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS4BL01/01/01005.jpg"}
                                        ] };
})(window);
