(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_349 = { Name: "三星 S3 Mini", Product: [
                                        { ProductId: "2326", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01001.jpg"},
                                        { ProductId: "2327", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01002.jpg"},
                                        { ProductId: "2328", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01003.jpg"},
                                        { ProductId: "2329", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01004.jpg"},
                                        { ProductId: "2330", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01005.jpg"},
                                        { ProductId: "2331", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01006.jpg"},
                                        { ProductId: "2332", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01007.jpg"},
                                        { ProductId: "2333", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01008.jpg"},
                                        { ProductId: "2334", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01009.jpg"},
                                        { ProductId: "2335", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01010.jpg"},
                                        { ProductId: "2336", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01011.jpg"},
                                        { ProductId: "2337", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01012.jpg"},
                                        { ProductId: "2338", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01013.jpg"},
                                        { ProductId: "2339", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01014.jpg"},
                                        { ProductId: "2340", PdcId: "349", ProdName: "Painted Soft Case For Samsung Galaxy S3 Mini - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPTTPU01/01/01015.jpg"},
                                        { ProductId: "2341", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01001.jpg"},
                                        { ProductId: "2342", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01002.jpg"},
                                        { ProductId: "2343", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01003.jpg"},
                                        { ProductId: "2344", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01004.jpg"},
                                        { ProductId: "2345", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01005.jpg"},
                                        { ProductId: "2346", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01006.jpg"},
                                        { ProductId: "2347", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01007.jpg"},
                                        { ProductId: "2348", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01008.jpg"},
                                        { ProductId: "2349", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01009.jpg"},
                                        { ProductId: "2350", PdcId: "349", ProdName: "Painted Leather Case For Samsung Galaxy S3 Mini - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIPLT02/01010.jpg"},
                                        { ProductId: "4173", PdcId: "349", ProdName: "Leaf Leather Case For Samsung Galaxy S3 Mini", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGS3MINIBL01/01/01005.jpg"}
                                        ] };
})(window);
