(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_365 = { Name: "三星 Core Prime", Product: [
                                        { ProductId: "3870", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01001.jpg"},
                                        { ProductId: "3871", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01002.jpg"},
                                        { ProductId: "3872", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01003.jpg"},
                                        { ProductId: "3873", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01004.jpg"},
                                        { ProductId: "3874", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01005.jpg"},
                                        { ProductId: "3875", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01006.jpg"},
                                        { ProductId: "3876", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01007.jpg"},
                                        { ProductId: "3877", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01008.jpg"},
                                        { ProductId: "3878", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01009.jpg"},
                                        { ProductId: "3879", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01010.jpg"},
                                        { ProductId: "3880", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01011.jpg"},
                                        { ProductId: "3881", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01012.jpg"},
                                        { ProductId: "3882", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01013.jpg"},
                                        { ProductId: "3883", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01014.jpg"},
                                        { ProductId: "3884", PdcId: "365", ProdName: "Painted Soft Case For Samsung Galaxy Core Prime - [PCSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PTTPU01/01/01015.jpg"},
                                        { ProductId: "3885", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01001.jpg"},
                                        { ProductId: "3886", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01002.jpg"},
                                        { ProductId: "3887", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01003.jpg"},
                                        { ProductId: "3888", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01004.jpg"},
                                        { ProductId: "3889", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01005.jpg"},
                                        { ProductId: "3890", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01006.jpg"},
                                        { ProductId: "3891", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01007.jpg"},
                                        { ProductId: "3892", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01008.jpg"},
                                        { ProductId: "3893", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01009.jpg"},
                                        { ProductId: "3894", PdcId: "365", ProdName: "Painted Leather Case For Samsung Galaxy Core Prime - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360PLT02/01010.jpg"},
                                        { ProductId: "4333", PdcId: "365", ProdName: "Leaf Leather Case For Samsung Galaxy Core Prime", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SAMSUNGG360BL01/01/01005.jpg"}
                                        ] };
})(window);
