(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_461 = { Name: "华硕 5", Product: [
                                        { ProductId: "3663", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01001.jpg"},
                                        { ProductId: "3664", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01002.jpg"},
                                        { ProductId: "3665", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01003.jpg"},
                                        { ProductId: "3666", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01004.jpg"},
                                        { ProductId: "3667", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01005.jpg"},
                                        { ProductId: "3668", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01006.jpg"},
                                        { ProductId: "3669", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01007.jpg"},
                                        { ProductId: "3670", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01008.jpg"},
                                        { ProductId: "3671", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01009.jpg"},
                                        { ProductId: "3672", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01010.jpg"},
                                        { ProductId: "3673", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01011.jpg"},
                                        { ProductId: "3674", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01012.jpg"},
                                        { ProductId: "3675", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01013.jpg"},
                                        { ProductId: "3676", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01014.jpg"},
                                        { ProductId: "3677", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01015.jpg"},
                                        { ProductId: "3678", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01016.jpg"},
                                        { ProductId: "3679", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01017.jpg"},
                                        { ProductId: "3680", PdcId: "461", ProdName: "Painted Soft Case For Asus Zenfone 5 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PTTPU01/01/01018.jpg"},
                                        { ProductId: "3681", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01001.jpg"},
                                        { ProductId: "3682", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01002.jpg"},
                                        { ProductId: "3683", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01003.jpg"},
                                        { ProductId: "3684", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01004.jpg"},
                                        { ProductId: "3685", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01005.jpg"},
                                        { ProductId: "3686", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01006.jpg"},
                                        { ProductId: "3687", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01007.jpg"},
                                        { ProductId: "3688", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01008.jpg"},
                                        { ProductId: "3689", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01009.jpg"},
                                        { ProductId: "3690", PdcId: "461", ProdName: "Painted Leather Case For Asus Zenfone 5 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/ASUS5PLT02/01010.jpg"},
                                        { ProductId: "4326", PdcId: "461", ProdName: "Frosted Matte Plastic Hard For Asus Zenfone 5", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/G00000290/G290_00004.jpg"}
                                        ] };
})(window);
