(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_391 = { Name: "索尼 M4", Product: [
                                        { ProductId: "3115", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01001.jpg"},
                                        { ProductId: "3116", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01002.jpg"},
                                        { ProductId: "3117", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01003.jpg"},
                                        { ProductId: "3118", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01004.jpg"},
                                        { ProductId: "3119", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01005.jpg"},
                                        { ProductId: "3120", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01006.jpg"},
                                        { ProductId: "3121", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01007.jpg"},
                                        { ProductId: "3122", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01008.jpg"},
                                        { ProductId: "3123", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01009.jpg"},
                                        { ProductId: "3124", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01010.jpg"},
                                        { ProductId: "3125", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0011]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01011.jpg"},
                                        { ProductId: "3126", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0012]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01012.jpg"},
                                        { ProductId: "3127", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0013]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01013.jpg"},
                                        { ProductId: "3128", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0014]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01014.jpg"},
                                        { ProductId: "3129", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0015]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01015.jpg"},
                                        { ProductId: "3130", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0016]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01016.jpg"},
                                        { ProductId: "3131", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0017]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01017.jpg"},
                                        { ProductId: "3132", PdcId: "391", ProdName: "Painted Soft Case For Sony Xperia M4 - [PSC0018]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PTTPU01/01/01018.jpg"},
                                        { ProductId: "3133", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01001.jpg"},
                                        { ProductId: "3134", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01002.jpg"},
                                        { ProductId: "3135", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01003.jpg"},
                                        { ProductId: "3136", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01004.jpg"},
                                        { ProductId: "3137", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01005.jpg"},
                                        { ProductId: "3138", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01006.jpg"},
                                        { ProductId: "3139", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01007.jpg"},
                                        { ProductId: "3140", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC008]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01008.jpg"},
                                        { ProductId: "3141", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC009]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01009.jpg"},
                                        { ProductId: "3142", PdcId: "391", ProdName: "Painted Leather Case For Sony Xperia M4 - [PLC0010]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/PhoneCase/SONYM4PLT02/01010.jpg"}
                                        ] };
})(window);
