(function (window) {
     if (!window.mikoor) { window.mikoor = {}; }
     mikoor.pdc_372 = { Name: "三星 Tab S", Product: [
                                        { ProductId: "4122", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01001.jpg"},
                                        { ProductId: "4123", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01002.jpg"},
                                        { ProductId: "4124", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01003.jpg"},
                                        { ProductId: "4125", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01004.jpg"},
                                        { ProductId: "4126", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01005.jpg"},
                                        { ProductId: "4127", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01006.jpg"},
                                        { ProductId: "4128", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T700 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT700PICC01/01/01007.jpg"},
                                        { ProductId: "4129", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC001]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01001.jpg"},
                                        { ProductId: "4130", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC002]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01002.jpg"},
                                        { ProductId: "4131", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC003]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01003.jpg"},
                                        { ProductId: "4132", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC004]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01004.jpg"},
                                        { ProductId: "4133", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC005]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01005.jpg"},
                                        { ProductId: "4134", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC006]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01006.jpg"},
                                        { ProductId: "4135", PdcId: "372", ProdName: "Painted Leather Case For Samsung Galaxy Tab S T800 - [PLC007]", Price: "$0", Currency: "USD", Url: "", MainPic: "http://www.ecdream.com/Database/Product/Electronics/TabletPCCase/SAMSUNGT800PICC01/01/01007.jpg"}
                                        ] };
})(window);
